baseURL = "https://joshstepp.com/"
languageCode = "en-us"
title = "Josh Stepp"
theme = "minimal"
copyright = "&copy; 2016-2019. All rights reserved."
googleAnalytics = "UA-89104888-1"


[params]
  author = "Josh Stepp"
  description = " 0x54 0x68 0x72 0x65 0x61 0x74 0x20 0x48 0x75 0x6e 0x74 0x65 0x72 "
  githubUsername = "joshstepp"
  accent = "green"
  showBorder = true
  backgroundColor = "white"
  font = "Source Code Pro" # should match the name on Google Fonts!
  highlight = true
  highlightStyle = "solarized-dark"

[menu]

  [[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    weight = 1
    identifier = "about"
    url = "/about/"
 [[menu.main]]
    name = "Now"
    weight = 2
    identifier = "now"
    url = "/now/"
  [[menu.main]]
    name = "Books"
    weight = 3
    identifier = "Books"
    url = "/recommendedreading/"
  [[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 5
    identifier = "Blog"

  

  [[menu.icon]]
    url = "mailto:joshstepp5@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/joshstepp/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/j0sh_stepp/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/joshstepp404/"
    name = "linkedin"
    weight = 4